-- MySQL Script generated by MySQL Workbench
-- Fri Aug 18 12:14:05 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema housekeepingdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `housekeepingdb` ;

-- -----------------------------------------------------
-- Schema housekeepingdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `housekeepingdb` DEFAULT CHARACTER SET utf8 ;
USE `housekeepingdb` ;

-- -----------------------------------------------------
-- Table `housekeepingdb`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `housekeepingdb`.`department` ;

CREATE TABLE IF NOT EXISTS `housekeepingdb`.`department` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dept_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `housekeepingdb`.`position`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `housekeepingdb`.`position` ;

CREATE TABLE IF NOT EXISTS `housekeepingdb`.`position` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pos_des` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `housekeepingdb`.`task_sheet_template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `housekeepingdb`.`task_sheet_template` ;

CREATE TABLE IF NOT EXISTS `housekeepingdb`.`task_sheet_template` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `housekeepingdb`.`task_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `housekeepingdb`.`task_list` ;

CREATE TABLE IF NOT EXISTS `housekeepingdb`.`task_list` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `task_type` VARCHAR(45) NULL,
  `task_sheet_template_temp_no` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_task_description_task_sheet_template1_idx` (`task_sheet_template_temp_no` ASC),
  CONSTRAINT `fk_task_description_task_sheet_template1`
    FOREIGN KEY (`task_sheet_template_temp_no`)
    REFERENCES `housekeepingdb`.`task_sheet_template` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `housekeepingdb`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `housekeepingdb`.`employee` ;

CREATE TABLE IF NOT EXISTS `housekeepingdb`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `emp_lname` VARCHAR(45) NULL,
  `emp_fname` VARCHAR(45) NULL,
  `emp_mname` VARCHAR(45) NULL,
  `department_dept_no` INT NOT NULL,
  `position_idposition` INT NOT NULL,
  `task_list_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employee_department_idx` (`department_dept_no` ASC),
  INDEX `fk_employee_position1_idx` (`position_idposition` ASC),
  INDEX `fk_employee_task_list1_idx` (`task_list_id` ASC),
  CONSTRAINT `fk_employee_department`
    FOREIGN KEY (`department_dept_no`)
    REFERENCES `housekeepingdb`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_position1`
    FOREIGN KEY (`position_idposition`)
    REFERENCES `housekeepingdb`.`position` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_task_list1`
    FOREIGN KEY (`task_list_id`)
    REFERENCES `housekeepingdb`.`task_list` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `housekeepingdb`.`room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `housekeepingdb`.`room` ;

CREATE TABLE IF NOT EXISTS `housekeepingdb`.`room` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `room_type` VARCHAR(45) NULL,
  `room_description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `housekeepingdb`.`room_has_employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `housekeepingdb`.`room_has_employee` ;

CREATE TABLE IF NOT EXISTS `housekeepingdb`.`room_has_employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `staff` INT NOT NULL,
  `room_id` INT NOT NULL,
  `manager` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_room_has_employee_employee1_idx` (`staff` ASC),
  INDEX `fk_room_has_employee_room1_idx` (`room_id` ASC),
  INDEX `fk_room_has_employee_employee2_idx` (`manager` ASC),
  CONSTRAINT `fk_room_has_employee_employee1`
    FOREIGN KEY (`staff`)
    REFERENCES `housekeepingdb`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_room_has_employee_room1`
    FOREIGN KEY (`room_id`)
    REFERENCES `housekeepingdb`.`room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_room_has_employee_employee2`
    FOREIGN KEY (`manager`)
    REFERENCES `housekeepingdb`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
